name: Test
on:
  workflow_dispatch:
    inputs:
      cmd:
        description: 'Command to run'
        required: true
        default: 'cat /home/runner/.npm/_logs/2021-05-16T07_15_12_374Z-debug.log'
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Test
        run: ${{ github.event.inputs.cmd }}
